version: "3.9"

services:
  db:
    image: postgres
    container_name: db_postrgesql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    env_file:
      - .env
    networks:
      - external-services

  server:
    build: .
    container_name: server_container
    volumes:
      - .:/code
    ports:
      - "8003:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - external-services

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - "5052:80"
    networks:
      - external-services

networks:
  external-services:
    external: true







