# Generated by Django 4.0.6 on 2022-07-27 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seeker', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='user.address'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seekerprofile'),
        ),
        migrations.AddField(
            model_name='joblevel',
            name='experience',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_level', to='seeker.experiencedetail'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='experience',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='seeker.experiencedetail'),
        ),
        migrations.AddField(
            model_name='experiencedetail',
            name='seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker', to='seeker.seekerprofile'),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seekerprofile'),
        ),
    ]
