# Generated by Django 4.0.6 on 2022-07-28 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.individualprofile'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.ManyToManyField(to='company.jobtype'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile'),
        ),
        migrations.AddField(
            model_name='companyratings',
            name='company_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile'),
        ),
    ]
