# Generated by Django 4.0.6 on 2022-07-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_type',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.ManyToManyField(to='company.jobtype'),
        ),
    ]
