# Generated by Django 4.0.6 on 2022-07-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostactivity',
            name='job_post',
        ),
        migrations.RemoveField(
            model_name='jobpostactivity',
            name='seeker_profile',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
        migrations.DeleteModel(
            name='JobPostActivity',
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
    ]
