# Generated by Django 4.0.6 on 2022-07-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
                ('starting_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('education_board', models.CharField(max_length=50)),
                ('university_name', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('starting_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(blank=True, choices=[('1', 'Seeker'), ('2', 'Provider'), ('3', 'Both')], default=None, max_length=1, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='media/individual')),
                ('date_of_birth', models.DateField()),
                ('primary_contact', models.CharField(max_length=14)),
                ('secondary_contact', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('institute_name', models.CharField(max_length=100)),
                ('starting_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('certificate', models.ImageField(blank=True, default=None, null=True, upload_to='media/certificate')),
                ('seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.individualprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.individualprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerSkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Expert')], max_length=1)),
                ('seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.individualprofile')),
                ('skill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.skillset')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('starting_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('description', models.TextField()),
                ('seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.individualprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_level', to='individual.experiencedetail')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='individual.experiencedetail')),
            ],
        ),
    ]
