# Generated by Django 4.0.6 on 2022-07-29 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('individual', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='user.address'),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiencedetail',
            name='seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual', to='individual.individualprofile'),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.individualprofile'),
        ),
    ]
